"use client";
import Header from "@/components/header";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "@/components/footer";
import ReduxProvider from "@/components/redux-provider";
import Background from "@/components/background-image";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Umut Cemre Can",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ReduxProvider>
          <Background>
            <Header />
            <main>{children}</main>
            <Footer />
          </Background>
        </ReduxProvider>
      </body>
    </html>
  );
}
