"use client";
import Header from "@/components/header";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "@/components/footer";
import ReduxProvider from "@/components/redux-provider";
import Background from "@/components/background-image";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { useRouter } from "next/navigation";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Umut Cemre Can",
  description: "Generated by create next app",
};

export default function LocaleLayout({ children, params: { locale } }) {
  const router = useRouter();

  let messages;
  try {
    messages = import(`../../messages/${locale}.json`).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={montserrat.className}>
        <ReduxProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Background>
              <Header />
              <main>{children}</main>
              <Footer />
            </Background>
          </NextIntlClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
